codecov:
  notify:
    require_ci_to_pass: no
coverage:
  precision: 2
  round: up
  range: "0"
  status:
    project:
      default:
        target: 0
        threshold: 100% # pass all pull requests for now.
        only_pulls: true
    patch:
      default:
        enabled: no
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: yes

ignore:
  - "vendor/"
  - "bin/"
  - "cmd/"
  - ".circleci"
  - ".github/"
  - "internal/mocks"
  - "build/"
  - "cerebro/cmd"
  - "web/cmd"
