version: "3.1"
services:
  postgres:
    container_name: comiccruncher_postgres
    image: postgres:10.5-alpine
    ports:
      - "5433:5432"
    volumes:
      - comiccruncher:/tmp
      - ./build/docker/postgres/postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: comiccruncher_db
      PGDATA: /tmp
  redis:
    container_name: comiccruncher_redis
    image: redis:3.2.12-alpine
    ports:
      - "6380:6380"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - comiccruncher:/data
      - ./build/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  comiccruncher:
    working_dir: /app/comiccruncher
    container_name: comiccruncher_backend
    ports:
      - "8001:8001"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/comiccruncher
      - ${GOPATH}/pkg/mod:/gocode/pkg/mod
    env_file:
      - .env
volumes:
  comiccruncher:
