version: "3.1"
services:
  postgres_test:
    container_name: comicruncher_postgres_test
    image: postgres:10.4-alpine
    ports:
      - "5434:5432"
    volumes:
      - ./build/docker/postgres-test/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: comiccruncher_db_test
  comiccruncher: # Override environment variables.
    environment:
      - "CC_ENVIRONMENT=test"
      - "CC_POSTGRES_TEST_HOST=comicruncher_postgres_test"
      - "CC_POSTGRES_TEST_PORT=5432"
      - "CC_POSTGRES_TEST_DB=comiccruncher_db_test"
      - "CC_POSTGRES_TEST_USER=root"
      - "CC_POSTGRES_TEST_PASSWORD=root"
