version: "3.1"
services:
  postgres_test:
    container_name: comiccruncher_postgres_test
    image: postgres:10.5-alpine
    ports:
      - "5434:5432"
    volumes:
      - comiccruncher_test:/tmp
      - ./build/docker/postgres/postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: comiccruncher_db_test
      PGDATA: /tmp
  comiccruncher: # Override environment variables.
    environment:
      - "CC_ENVIRONMENT=test"
      - "CC_POSTGRES_TEST_HOST=comiccruncher_postgres_test"
      - "CC_POSTGRES_TEST_PORT=5432"
      - "CC_POSTGRES_TEST_DB=comiccruncher_db_test"
      - "CC_POSTGRES_TEST_USER=root"
      - "CC_POSTGRES_TEST_PASSWORD=root"
      - "CC_CDN_URL=https://d2jsu6fyd1g4ln.cloudfront.net"
      - "CC_JWT_AUTH_SECRET=test1"
      - "CC_JWT_SIGNING_SECRET=test2"
      - "CC_AUTH_TOKEN=test"
volumes:
  comiccruncher_test:
