version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
workflows:
  vet-test-build-deploy:
    jobs:
      - test_and_build:
          context: comiccruncher
          filters:
            tags:
              only: /.*/
      - codecov:
          context: comiccruncher
          requires:
            - test_and_build
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^v.*/
      - build_and_push_tasks:
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build_and_push_api:
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build_and_push_tasks
            - build_and_push_api
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  test_and_build:
    machine: true
    working_directory: ~/app/comiccruncher
    environment:
      GOPATH: ~/gocode/
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-{{ checksum "go.sum" }}
      - run:
          name: Build the test container.
          command: make docker-up-test
      - run:
          name: Install the dependencies.
          command: make docker-mod-download
      - save_cache:
          key: gomod-{{ checksum "go.sum" }}
          paths:
            - "~/gocode/pkg/mod"
      - run:
          name: Run database migrations for the test db.
          command: make docker-migrations-test
      - run:
          name: Run the tests.
          command: make docker-test
      - save_cache:
          key: coverage-{{ .Branch }}-{{ .Revision }}
          paths:
            - "./coverage.txt"
      - run:
          name: Build the build images.
          command: make docker-build-tasks
      - run:
          name: Build the application binaries
          command: make docker-build-webapp
  codecov:
    machine: true
    working_directory: ~/app/comiccruncher
    environment:
      GOPATH: ~/gocode/
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-{{ checksum "go.sum" }}
      - restore_cache:
          keys:
            - coverage-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Code coverage
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -f coverage.txt -X fix
  build_and_push_tasks:
    machine: true
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run:
          name: Build the Docker image for app tasks.
          command: docker build -f ./build/deploy/api/Dockerfile -t comiccruncher/tasks:latest .
      - run:
          name: Push the image to the Docker repository.
          command: |
            docker tag comiccruncher/tasks:latest 570480763436.dkr.ecr.us-east-1.amazonaws.com/comiccruncher/tasks:latest
            docker push 570480763436.dkr.ecr.us-east-1.amazonaws.com/comiccruncher/tasks:latest
  build_and_push_api:
    machine: true
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run:
          name: Build the Docker image
          command: docker build -f ./build/deploy/api/Dockerfile -t comiccruncher/api:latest .
      - run:
          name: Publish the Docker image
          command: |
            docker tag comiccruncher/api:latest 570480763436.dkr.ecr.us-east-1.amazonaws.com/comiccruncher/api:latest
            docker push 570480763436.dkr.ecr.us-east-1.amazonaws.com/comiccruncher/api:latest
  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "8f:f7:d9:2c:ee:0a:6c:86:c2:d9:55:3b:68:2a:ee:d8"
            - "06:c5:51:61:f5:df:f2:bd:57:37:5d:b0:8c:39:81:be"
      - run:
          name: Upload deploy files.
          command: make remote-upload-deployfiles
      - run:
          name: Run deploy scripts.
          command: make remote-deploy
