version: 2
workflows:
  version: 2
  vet-test-build-deploy:
    jobs:
      - test_and_build:
          context: comiccruncher
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^v.*/
      - vet_and_codecov:
          context: comiccruncher
          requires:
            - test_and_build
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^v.*/
      - deploy_tasks:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_webapps:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  test_and_build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Build the test container.
          command: make docker-up-test
      - run:
          name: Generate the .netrc file for getting the private repository.
          command: GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} make netrc > /dev/null
      - run:
          name: Install the dependencies.
          command: make docker-dep-ensure
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"
      - run:
          name: Run database migrations for the test db.
          command: make docker-migrations-test
      - run:
          name: Run the tests.
          command: make docker-test
      - run:
          name: Cleanup netrc
          command: rm .netrc
      - save_cache:
          key: coverage-{{ .Branch }}-{{ .Revision }}
          paths:
            - "./coverage.txt"
      - run:
          name: Build the build container.
          command: make docker-up
      - run:
          name: Build the application binaries
          command: make docker-build-xcompile
      - save_cache:
          key: bin-{{ .Revision }}
          paths:
            - "./bin"
  vet_and_codecov:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - coverage-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Vet the files and report any errors.
          command: make docker-vet
      - run:
          name: Code coverage
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -f coverage.txt -X fix
  deploy_tasks:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            -  bin-{{ .Revision }}
      - add_ssh_keys:
          fingerprints:
            - "31:c6:46:c7:d8:8d:f4:2a:b5:ac:75:c0:4c:f0:b1:9d"
      - run:
          name: Deploy migrations.
          command: make remote-deploy-migrations
      - run:
          name: Deploy cerebro.
          command: make remote-deploy-cerebro
      - run:
          name: Deploy comic.
          command: make remote-deploy-comic
  deploy_webapps:
      machine: true
      steps:
      - checkout
      - restore_cache:
          keys:
            - bin-{{ .Revision }}
      - add_ssh_keys:
            fingerprints:
              - "5f:70:a7:b4:80:40:0a:16:90:cf:a5:a6:af:aa:35:de"
              - "48:9c:e0:fe:c9:3f:2f:40:1f:ba:d1:38:c9:ea:72:0a"
              - "31:c6:46:c7:d8:8d:f4:2a:b5:ac:75:c0:4c:f0:b1:9d"
      - run:
            name: Deploy webapp.
            command: make remote-deploy-webapps
