version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
workflows:
  vet-test-build-deploy:
    jobs:
      - test_and_build:
          context: comiccruncher
          filters:
            tags:
              only: /.*/
      - codecov:
          context: comiccruncher
          requires:
            - test_and_build
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^v.*/
      - deploy_tasks:
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_webapps:
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  test_and_build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Build the test container.
          command: make docker-up-test
      - run:
          name: Generate the .netrc file for getting the private repository.
          command: GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} make netrc > /dev/null
      - run:
          name: Install the dependencies.
          command: make docker-dep-ensure
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"
      - run:
          name: Run database migrations for the test db.
          command: make docker-migrations-test
      - run:
          name: Run the tests.
          command: make docker-test
      - run:
          name: Cleanup netrc
          command: rm .netrc
      - save_cache:
          key: coverage-{{ .Branch }}-{{ .Revision }}
          paths:
            - "./coverage.txt"
      - run:
          name: Build the build container.
          command: make docker-up
      - run:
          name: Build the application binaries
          command: make docker-build-xcompile
      - save_cache:
          key: bin-{{ .Revision }}
          paths:
            - "./bin"
            - "./build/deploy/api/bin"
  codecov:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - coverage-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Code coverage
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -f coverage.txt -X fix
  deploy_tasks:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            -  bin-{{ .Revision }}
      - add_ssh_keys:
          fingerprints:
            - "8f:f7:d9:2c:ee:0a:6c:86:c2:d9:55:3b:68:2a:ee:d8"
      - run:
          name: Deploy migrations.
          command: make remote-deploy-migrations
      - run:
          name: Deploy cerebro.
          command: make remote-deploy-cerebro
      - run:
          name: Deploy comic.
          command: make remote-deploy-comic
  deploy_webapps:
      machine: true
      steps:
      - checkout
      - restore_cache:
          keys:
            - bin-{{ .Revision }}
            - vendor-{{ checksum "Gopkg.lock" }}
      - add_ssh_keys:
            fingerprints:
              - "8f:f7:d9:2c:ee:0a:6c:86:c2:d9:55:3b:68:2a:ee:d8"
      - aws-ecr/ecr-login
      - run:
          name: Generate netrc
          command: GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} make netrc > /dev/null
      - run:
          name: Build the Docker image
          command: docker build -f ./build/deploy/api/Dockerfile -t comiccruncher/api:latest .
      - run:
          name: Publish the Docker image
          command: |
            docker tag comiccruncher/api:latest
            docker push 570480763436.dkr.ecr.us-east-1.amazonaws.com/comiccruncher/api:latest
      - run:
            name: Deploy webapp.
            command: make remote-deploy-webapps
