version: 2
workflows:
  version: 2
  vet-test-build-deploy:
    jobs:
      - test_and_build:
          context: comiccruncher
          filters:
            tags:
              only: /.*/
      - vet_and_codecov:
          requires:
            - test_and_build
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - deploy_tasks:
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_webapps:
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  test_and_build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: Build the test container.
          command: make docker-up-test
      - run:
          name: Generate the .netrc file for getting the private repository.
          command: GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} make netrc > /dev/null
      - run:
          name: Install the dependencies.
          command: make docker-dep-ensure
      - save_cache:
          key: vendor-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"
      - run:
          name: Run database migrations for the test db.
          command: make docker-migrations-test
      - run:
          name: Run the tests.
          command: make docker-test
      - run:
          name: Cleanup netrc
          command: rm .netrc
      - run:
          name: Build the build container.
          command: make docker-up
      - run:
          name: Build the application binaries
          command: make docker-build-xcompile
      - save_cache:
          key: bin-{{ .Branch }}-{{ .Revision }}
          paths:
            - "./bin"
  vet_and_codecov:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: Vet the files and report any errors.
          command: make docker-vet
      - run:
          name: Code coverage
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -f coverage.txt -X fix
  deploy_tasks:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            -  bin-{{ .Branch }}-{{ .Revision }}
      - add_ssh_keys:
          fingerprints:
            - "d3:5c:3f:5e:15:21:8f:1d:6c:e5:61:41:45:2a:82:16"
      - run:
          name: Deploy migrations.
          command: make remote-deploy-migrations
      - run:
          name: Deploy cerebro.
          command: make remote-deploy-cerebro
  deploy_webapps:
      machine: true
      steps:
      - checkout
      - restore_cache:
          keys:
            - bin-{{ .Branch }}-{{ .Revision }}
      - add_ssh_keys:
            fingerprints:
              - "d3:5c:3f:5e:15:21:8f:1d:6c:e5:61:41:45:2a:82:16"
              - "87:28:6d:80:be:93:da:78:7f:3c:18:36:f8:4c:57:4d"
              - "d2:0f:21:f7:02:18:2e:8d:08:39:17:70:e9:ec:e0:74"
      - run:
            name: Deploy webapp.
            command: make remote-deploy-webapps
